### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by InDieTasten** [iaincollins/docker-deploy-webhook#2]
Can you consider adding a OSS license to this project. I would like to make an adjustment to it for my own needs, but without license, I won't do it.

Thanks in advance
~InDieTasten

**Comment by levino** [comment]
License is ISC

**https://github.com/iaincollins/docker-deploy-webhook/blob/b2661bbd00bb5a25730e7f2ff1e267deefd71831/package.json#L11**

**Comment by InDieTasten** [comment]
I forgot about package.json having license info too. I'm always just looking for a LICENSE txt or md file. #5 Seems to be adding such a file that I expected to be there first.

**Comment by iaincollins** [comment]
Yeah it should really have a LICENSE file to spell it out more explicitly, have merged that in now, thanks for the PR!
